### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by khazifire** [khazifire/DripUI#1]
Invalid urls path should show a 404 page which should have a button to return back to landing page

**Comment by zabihhaqqani** [comment]
Hey, @khazifire I would like to work on this issue.

**Comment by Michelle031** [comment]
Hello,
Can I be assigned this issue, I have done something similar

**Comment by Michelle031** [comment]
I am done with the 404 page, can you please assign the issue to me so I can make a pull request.
Thank you.

**Comment by DugarRishab** [comment]
@khazifire I want to contribute to this issue.

**Comment by khazifire** [comment]
@DugarRishab already worked on it, you can look through the issues, and see if you can find something to contribute to (or you can suggest issues that can be fixed) Thank you
