### ISSUE TITLE
Make the nav bar responsive on mobile

### ISSUE THREAD

**Issue by khazifire** [khazifire/DripUI#15]
Hemberger menu can be added on mobile

![image](https://user-images.githubusercontent.com/73513866/193436717-ac7bd318-ea97-470b-9520-292b3b3122a5.png)

**Comment by Dun-sin** [comment]
hi @khazifire can i take this?

**Comment by vivek-dhiman** [comment]
@khazifire Hey, I would like to work on this issue. Please assign this to me.

**Comment by khazifire** [comment]
@Dun-sin  @vivek-dhiman i assigned it to both of you

**Comment by Dun-sin** [comment]
> @Dun-sin  @vivek-dhiman i assigned it to both of you 

I think one person is enough for this, pick one

**Comment by khazifire** [comment]
@Dun-sin  you can work on it since you were the first one here

![image](https://user-images.githubusercontent.com/73513866/193438631-759d2a8b-afe3-4ed0-8e9d-59fd6fbe4dc2.png)

**Comment by utkarsh-1602** [comment]
![Screenshot 2022-10-03 235402](https://user-images.githubusercontent.com/79980596/193650782-3b7e4bdc-973e-40f1-960a-7bfdb7611a2d.png)

made some changes
