### ISSUE TITLE
Create Header Component 

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [khazifire/DripUI#17]
I'll like to take this on as the section of the site has a coming soon on it

**Comment by khazifire** [comment]
That will be awesome, I assigned it to you, make sure you look at how the pages for the other components were structured

**Comment by Onyelaudochukwuka** [comment]
Alright I'll do that 💪🏽

**Comment by Elishaokon13** [comment]
I think this has been resolved
@khazifire

**Comment by khazifire** [comment]
@Elishaokon13 can you run `npm build` and try to resolve the errors then create another pull request
