### ISSUE TITLE
Avoid Getting Element Directly From The Dom In React

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [khazifire/DripUI#20]
![Screen Shot 2022-10-02 at 3 51 17 PM](https://user-images.githubusercontent.com/82924100/193460508-f0a93581-f713-43e4-a2a5-160643093cfc.png)
This should be fixed with the e(event) keyword which is an inbuilt method for such tasks rather than getting the element directly from the D.O.M.
I'l love to fix this if assigned to me

**Comment by khazifire** [comment]
@Onyelaudochukwuka i assigned it to you, if possible that function could be made available globally, because it will be used in most of the files

**Comment by Onyelaudochukwuka** [comment]
Ok I think the global option is a great idea let me work on that
