### ISSUE TITLE
[FEATURE] Create Drip CLI for managing components

### ISSUE THREAD

**Issue by slim-codes** [khazifire/DripUI#25]
### What is the new or updated feature that you are suggesting?

Create a lightweight that facilitates the creation, modification, and management of components

- This will remove the need for navigating in and out of folders. The CLI will take care of putting the generated components in the required folders

- Something like:
`drip generate card component-name`
`drip generate button component-name` and so on

I'd love to work on this if you approve @khazifire

**Comment by Onyelaudochukwuka** [comment]
we can use [https://lego-build.github.io/docs](https://lego-build.github.io/docs) for generating the componets, their structure is flexible enough for this

**Comment by khazifire** [comment]
@slim-codes I assigned it to you, its a pretty cool idea

**Comment by slim-codes** [comment]
Working on it

**Comment by slim-codes** [comment]
@khazifire 

I just completed the basic features of the CLI. I'm about to publish it and create a PR for it. However, I'd like to suggest that you create a new Repo for it. Something like **Drip-CLI** maybe. I could also make direct PR for it right now if you'd prefer for it to live inside this repo. I'm awaiting your feedback

**Comment by khazifire** [comment]
@slim-codes you can create a PR

**Comment by slim-codes** [comment]
> @slim-codes you can create a PR
> 

Alright then! 
Will do by the end of the day
