### ISSUE TITLE
[BUG] Items overlapping the Navbar

### ISSUE THREAD

**Issue by rupali-codes** [khazifire/DripUI#26]
### What is the current behavior?
Components overlapping Navbar

### Steps to Reproduce

If the current behavior is a bug, if possible please provide the steps to reproduce.

### What is the expected behavior?

The expected behavior is that Components shouldn't overlap Navbar

### What should DripUI do ?

Adding a z-index and bg-white will resolve this.

### Screenshot

![image](https://user-images.githubusercontent.com/78981177/193872875-3755004c-ad88-4185-8792-1d626b3100a0.png)

**Comment by rupali-codes** [comment]
Hey @khazifire,  can this issue be assigned to me?

**Comment by khazifire** [comment]
Hey @rupali-codes yeah you can work on it

That's very strange hmmh, it was fine before, but as you said it's probably something to do with the z position
