### ISSUE TITLE
Header component not vertically aligned

### ISSUE THREAD

**Issue by mfonPeeter** [khazifire/DripUI#31]
![Drip UI Header Component)](https://user-images.githubusercontent.com/105684251/194544840-e2524ab8-83b2-4fb7-8a8a-23bba29046ff.png)

I noticed the contents of the header component are not vertically aligned in the mobile view. That is the menu icon on the right is not vertically aligned with the contents on the left. Please could I be assigned this issue under hacktoberfest.

**Comment by khazifire** [comment]
@mfonPeeter ohh thank you for letting me know, do you want to work on it?

**Comment by mfonPeeter** [comment]
Yes, I will love to. And if possible could it be assigned under hacktoberfest?

**Comment by mfonPeeter** [comment]
Thanks. I will get to work
