### ISSUE TITLE
[DOCUMENTATION FIX] Missing Tailwindcss link in the readme 

### ISSUE THREAD

**Issue by Dhruv-Gajjar** [khazifire/DripUI#41]
## What docs page needs to be fixed?

- **Section**: Tech Stack section in read me
- **Page**:

## What is the problem?
Tailwindcss links redirects to 404 page no found
## What should be changed to fix the problem?
Add tailwindcss official website link

**Comment by haszankauna** [comment]
I'll like this issue to be assigned to me.
