### ISSUE TITLE
[BUG] Inconsistent Responsive MENU / Navbar on different mobiles.

### ISSUE THREAD

**Issue by TreciaKS** [khazifire/DripUI#43]
### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.

### What is the current behavior?

What does Drip-ui do wrong?

- #### Inconsistent responsive menu width on different mobiles
<img width="1267" alt="Screenshot 2023-04-13 at 18 43 08" src="https://user-images.githubusercontent.com/82657928/231828695-2c57a910-8ed7-4027-b436-74ef20a138e3.png">

<img width="1253" alt="Screenshot 2023-04-13 at 18 43 33" src="https://user-images.githubusercontent.com/82657928/231828732-9c8383f8-31ad-434f-8724-792f3e596054.png">

- #### Menu streches too widely (Reaches edge of screen)
Note how the GitHub logo is almost cut out.
<img width="815" alt="Screenshot 2023-04-13 at 18 44 08" src="https://user-images.githubusercontent.com/82657928/231828779-37b8518e-8e3f-4b00-8b74-80332a57c81f.png">

### Steps to Reproduce
If the current behavior is a bug, if possible please provide the steps to reproduce.
- What does reproduce mean? Not understanding this question.

### What is the expected behavior?
- The menu's be consistent throught browsers
- Navbar not to stretch out

What should DripUI do ?

- To avoid streching of navbar, apply margin (mx-4) while also applying styling that will wrap content until breakpoint for responsiveness is applied.
- Avoid using percentaged width (w-1/2 or 33%) as it does not provide a consistent width. Instead use w-fit or rem defined value.
- 
### Environment Details

Which versions of npm, and which browser and OS are affected by this issue?
- Chrome_ version 112.0.5615.49 (Official Build) (arm64)
@khazifire

**Comment by khazifire** [comment]
Thanks for the heads-up i will look into it.

I'm actually planning on restructuring  the whole project soon, so by then this bug will be resolved
