### ISSUE TITLE
Add some margin on the left and right side of the site.

### ISSUE THREAD

**Issue by sainathd07** [khazifire/DripUI#7]
It seems like there is no margin and padding at the left and right edges of the site. Add it to make it look good

**Comment by khazifire** [comment]
desktop version has more than enough margin and padding, i guess you are referring to smaller screen (mobile)

**Comment by sainathd07** [comment]
![image](https://user-images.githubusercontent.com/67309212/192464125-558170e6-5016-4b45-af45-597514621952.png)

I was referring to the desktop. The margin and padding are good on mobile screens.

**Comment by sainathd07** [comment]
Left side of the page - near text components

**Comment by khazifire** [comment]
ohh that's strange, i will look into it

**Comment by Tusharjain123** [comment]
Hey,
Can I work on this issue?

**Comment by DugarRishab** [comment]
Hey, I would like to contribute to this issue

**Comment by khazifire** [comment]
@DugarRishab i assigned it to you, Thanks!

**Comment by DugarRishab** [comment]
@khazifire I have opened up a pull request for this issue. Please check it out.
