### ISSUE TITLE
Add link to GitHub repo

### ISSUE THREAD

**Issue by khazifire** [khazifire/DripUI#9]
in the header, there should be a link to link back to this repository

**Comment by samyukthasudhakar** [comment]
Hi @Khazifire ! I'd like to take this up, please assign this to me. Thanks !

**Comment by khazifire** [comment]
@samyukthasudhakar  I have assigned the issue to you, Thanks!
for the icon you can use ([remix icons](https://remixicon.com/) )  --- its already installed in the project

**Comment by samyukthasudhakar** [comment]
#14

**Comment by khazifire** [comment]
Thank you @samyukthasudhakar for your contribution, I will review it
